- ignore: {}
- hint: {name: Use if}
- hint: {name: Use head}
- hint: {name: Use >}
- hint: {name: Use >=}
- hint: {name: Use <}
- hint: {name: Use <=}
- hint: {name: Use minimum}
- hint: {name: Use maximum}
- hint: {name: Use head}
- hint: {name: Use last}
- hint: {name: Use guard}
- hint: {name: Use const}
- hint: {name: Redundant bracket}
- hint: {name: Evaluate}